### PR TITLE
update scala versions

### PR DESCRIPTION
**Pull request by sideeffffect**
fixes https://github.com/ghik/silencer/issues/35

### CODE REVIEW

**Comment by sideeffffect** [comment]
fixes https://github.com/ghik/silencer/issues/35

**Comment by ennru** [comment]
Looks like there are some API changes to adopt to https://travis-ci.org/ghik/silencer/jobs/587844664#L500

**Comment by sideeffffect** [comment]
yep, internal API changed... I'm at loss here and don't know how to update this :frowning_face: 
if you know, feel free to pick this up after me :wink:

**Comment by lrytz** [comment]
There's a PR already with the necessary changes: https://github.com/ghik/silencer/pull/33

**Comment by ghik** [comment]
Superseded by #33

**Pull request closed without merging**
