### PR TITLE
Add 2.12.14

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Scala 2.12.14 is released. This PR aims to add it.

https://github.com/scala/scala/releases/tag/v2.12.14

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @ghik . Could you review this PR?

**Comment by dongjoon-hyun** [comment]
I added `Download` and `Inflate` sections for Scala 2.12.14 too. Could you trigger CI once more?

**Comment by ghik** [comment]
Thank you!

**Comment by dongjoon-hyun** [comment]
Thank you so much, @ghik !

**Pull request merged**
